openapi: 3.0.1
info:
  description: Meetings Service For HubSpot Sales
  title: Scheduler Meetings
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: PROFESSIONAL
    sales: PROFESSIONAL
    service: PROFESSIONAL
    cms: PROFESSIONAL
  x-hubspot-api-use-case: "You need to get a list of meeting links or book meetings,\
    \ or you need to create an interface so customers can book meetings with your\
    \ team."
  x-hubspot-related-documentation:
  - name: Meetings guide
    url: https://developers.hubspot.com/docs/reference/api/crm/engagements/meetings
  x-hubspot-introduction: Use the Meetings links API to retrieve information about
    meetings created through a scheduling page. You can also book a meeting with a
    scheduling page through the API.
servers:
- url: https://api.hubapi.com
tags:
- name: Meetings links
paths:
  /scheduler/v3/meetings/meeting-links/book/{slug}:
    get:
      operationId: "get-/scheduler/v3/meetings/meeting-links/book/{slug}"
      parameters:
      - description: ""
        explode: false
        in: path
        name: slug
        required: true
        schema:
          type: string
        style: simple
      - description: ""
        explode: true
        in: query
        name: timezone
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalBookingInfo'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - scheduler.meetings.meeting-link.read
      - private_apps:
        - scheduler.meetings.meeting-link.read
      tags:
      - Meetings links
  /scheduler/v3/meetings/meeting-links:
    get:
      operationId: get-/scheduler/v3/meetings/meeting-links
      parameters:
      - description: ""
        explode: true
        in: query
        name: after
        required: false
        schema:
          type: string
        style: form
      - description: ""
        explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - description: ""
        explode: true
        in: query
        name: name
        required: false
        schema:
          type: string
        style: form
      - description: ""
        explode: true
        in: query
        name: organizerUserId
        required: false
        schema:
          type: string
        style: form
      - description: ""
        explode: true
        in: query
        name: type
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionResponseWithTotalExternalLinkMetadataForwardPaging'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - scheduler.meetings.meeting-link.read
      - private_apps:
        - scheduler.meetings.meeting-link.read
      tags:
      - Meetings links
  /scheduler/v3/meetings/meeting-links/book:
    post:
      operationId: post-/scheduler/v3/meetings/meeting-links/book
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalMeetingBooking'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalMeetingBookingResponse'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.deals.write
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.goals.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.goals.write
      - private_apps:
        - crm.objects.contacts.sensitive.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.appointments.sensitive.write
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.schemas.contacts.write
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.schemas.contacts.write
        - tickets
      - oauth2:
        - crm.schemas.contacts.write
        - tickets
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.companies.sensitive.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.deals.sensitive.write
      - private_apps:
        - crm.schemas.contacts.write
        - tickets.sensitive
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.line_items.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.deals.highly_sensitive.write
      - private_apps:
        - crm.objects.listings.write
        - crm.schemas.contacts.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.listings.write
        - crm.schemas.contacts.write
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.companies.highly_sensitive.write
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
        - crm.schemas.contacts.write
      - private_apps:
        - crm.objects.deals.highly_sensitive.write.v2
        - crm.schemas.contacts.write
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
        - crm.schemas.contacts.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.companies.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.appointments.sensitive.write.v2
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.appointments.sensitive.write.v2
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.appointments.write
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.courses.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.courses.write
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.appointments.write
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.companies.write
      - oauth2:
        - crm.schemas.contacts.write
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.contacts.write
        - tickets.sensitive.v2
      - private_apps:
        - crm.schemas.contacts.write
        - tickets.highly_sensitive
      - private_apps:
        - crm.objects.companies.sensitive.write.v2
        - crm.schemas.contacts.write
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
        - crm.schemas.contacts.write
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.services.write
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.services.write
      - private_apps:
        - crm.objects.contacts.highly_sensitive.write
      - oauth2:
        - crm.schemas.contacts.write
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - crm.schemas.contacts.write
        - crm.objects.deals.sensitive.write.v2
      - private_apps:
        - crm.schemas.contacts.write
        - tickets.highly_sensitive.v2
      - private_apps:
        - crm.objects.companies.highly_sensitive.write.v2
        - crm.schemas.contacts.write
      tags:
      - Meetings links
  /scheduler/v3/meetings/meeting-links/book/availability-page/{slug}:
    get:
      operationId: "get-/scheduler/v3/meetings/meeting-links/book/availability-page/{slug}"
      parameters:
      - description: ""
        explode: false
        in: path
        name: slug
        required: true
        schema:
          type: string
        style: simple
      - description: ""
        explode: true
        in: query
        name: timezone
        required: false
        schema:
          type: string
        style: form
      - description: ""
        explode: true
        in: query
        name: monthOffset
        required: false
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalLinkAvailabilityAndBusyTimes'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - scheduler.meetings.meeting-link.read
      - private_apps:
        - scheduler.meetings.meeting-link.read
      tags:
      - Meetings links
components:
  responses:
    Error:
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
      description: An error occurred.
  schemas:
    ExternalMeetingBooking:
      example:
        duration: 0
        firstName: firstName
        lastName: lastName
        likelyAvailableUserIds:
        - likelyAvailableUserIds
        - likelyAvailableUserIds
        timezone: timezone
        legalConsentResponses:
        - communicationTypeId: communicationTypeId
          consented: true
        - communicationTypeId: communicationTypeId
          consented: true
        startTime: 2000-01-23T04:56:07.000+00:00
        formFields:
        - name: name
          value: value
        - name: name
          value: value
        locale: locale
        slug: slug
        email: email
      properties:
        duration:
          format: int64
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        likelyAvailableUserIds:
          items:
            type: string
          type: array
        timezone:
          type: string
        legalConsentResponses:
          items:
            $ref: '#/components/schemas/ExternalLegalConsentResponse'
          type: array
        startTime:
          format: date-time
          type: string
        formFields:
          items:
            $ref: '#/components/schemas/ExternalBookingFormField'
          type: array
        locale:
          type: string
        slug:
          type: string
        email:
          type: string
      required:
      - duration
      - email
      - firstName
      - formFields
      - lastName
      - legalConsentResponses
      - likelyAvailableUserIds
      - slug
      - startTime
      type: object
    ExternalMeetingAvailability:
      example:
        startMillisUtc: 1
        endMillisUtc: 1
      properties:
        startMillisUtc:
          format: int32
          type: integer
        endMillisUtc:
          format: int32
          type: integer
      required:
      - endMillisUtc
      - startMillisUtc
      type: object
    ExternalMeetingsLinkSettings:
      example:
        redirectUrl: redirectUrl
        startTimeIncrementMinutes: startTimeIncrementMinutes
        guestSettings:
          maxGuestCount: 0
          canAddGuests: true
        language: language
        availability:
          key:
            start: 6
            end: 1
        locale: locale
        ownerPrioritized: true
        legalConsentOptions:
          legitimateInterestSubscriptionTypes:
          - 5
          - 5
          processingConsentCheckboxLabel: processingConsentCheckboxLabel
          communicationConsentText: communicationConsentText
          legitimateInterestLegalBasis: LEGITIMATE_INTEREST_PQL
          processingConsentType: processingConsentType
          privacyPolicyText: privacyPolicyText
          processingConsentText: processingConsentText
          communicationConsentCheckboxes:
          - communicationTypeId: communicationTypeId
            label: label
            required: true
          - communicationTypeId: communicationTypeId
            label: label
            required: true
          processingConsentFooterText: processingConsentFooterText
          isLegitimateInterest: true
        welcomeScreenInfo:
          useCompanyLogo: true
          description: description
          showWelcomeScreen: true
          title: title
          logoUrl: logoUrl
        meetingBufferTime: 5
        weeksToAdvertise: 2
        displayInfo:
          publicDisplayAvatarOption: publicDisplayAvatarOption
          companyAvatar: companyAvatar
          avatar: avatar
          headline: headline
        durations:
        - 7
        - 7
        location: location
        formFields:
        - isRequired: true
          name: name
          options:
          - hidden: true
            displayOrder: 9
            doubleData: 3.616076749251911
            description: description
            readOnly: true
            label: label
            value: value
          - hidden: true
            displayOrder: 9
            doubleData: 3.616076749251911
            description: description
            readOnly: true
            label: label
            value: value
          isCustom: true
          label: label
          type: type
          fieldType: fieldType
        - isRequired: true
          name: name
          options:
          - hidden: true
            displayOrder: 9
            doubleData: 3.616076749251911
            description: description
            readOnly: true
            label: label
            value: value
          - hidden: true
            displayOrder: 9
            doubleData: 3.616076749251911
            description: description
            readOnly: true
            label: label
            value: value
          isCustom: true
          label: label
          type: type
          fieldType: fieldType
        legalConsentEnabled: true
        customAvailabilityEndDate: 2
        customAvailabilityStartDate: 4
      properties:
        redirectUrl:
          type: string
        startTimeIncrementMinutes:
          type: string
        guestSettings:
          $ref: '#/components/schemas/ExternalGuestSettings'
        language:
          type: string
        availability:
          additionalProperties:
            $ref: '#/components/schemas/ExternalClosedRange'
          type: object
        locale:
          type: string
        ownerPrioritized:
          type: boolean
        legalConsentOptions:
          $ref: '#/components/schemas/ExternalLegalConsentOptions'
        welcomeScreenInfo:
          $ref: '#/components/schemas/ExternalMeetingsWelcomeScreenInfo'
        meetingBufferTime:
          format: int32
          type: integer
        weeksToAdvertise:
          format: int32
          type: integer
        displayInfo:
          $ref: '#/components/schemas/ExternalLinkDisplayInfo'
        durations:
          items:
            format: int64
            type: integer
          type: array
        location:
          type: string
        formFields:
          items:
            $ref: '#/components/schemas/ExternalLinkFormField'
          type: array
        legalConsentEnabled:
          type: boolean
        customAvailabilityEndDate:
          format: int64
          type: integer
        customAvailabilityStartDate:
          format: int64
          type: integer
      required:
      - availability
      - durations
      - formFields
      - legalConsentEnabled
      - meetingBufferTime
      - ownerPrioritized
      - startTimeIncrementMinutes
      - weeksToAdvertise
      type: object
    ExternalClosedRange:
      example:
        start: 6
        end: 1
      properties:
        start:
          format: int32
          type: integer
        end:
          format: int32
          type: integer
      required:
      - end
      - start
      type: object
    ExternalBookingInfo:
      example:
        linkId: linkId
        customParams:
          redirectUrl: redirectUrl
          startTimeIncrementMinutes: startTimeIncrementMinutes
          guestSettings:
            maxGuestCount: 0
            canAddGuests: true
          language: language
          availability:
            key:
              start: 6
              end: 1
          locale: locale
          ownerPrioritized: true
          legalConsentOptions:
            legitimateInterestSubscriptionTypes:
            - 5
            - 5
            processingConsentCheckboxLabel: processingConsentCheckboxLabel
            communicationConsentText: communicationConsentText
            legitimateInterestLegalBasis: LEGITIMATE_INTEREST_PQL
            processingConsentType: processingConsentType
            privacyPolicyText: privacyPolicyText
            processingConsentText: processingConsentText
            communicationConsentCheckboxes:
            - communicationTypeId: communicationTypeId
              label: label
              required: true
            - communicationTypeId: communicationTypeId
              label: label
              required: true
            processingConsentFooterText: processingConsentFooterText
            isLegitimateInterest: true
          welcomeScreenInfo:
            useCompanyLogo: true
            description: description
            showWelcomeScreen: true
            title: title
            logoUrl: logoUrl
          meetingBufferTime: 5
          weeksToAdvertise: 2
          displayInfo:
            publicDisplayAvatarOption: publicDisplayAvatarOption
            companyAvatar: companyAvatar
            avatar: avatar
            headline: headline
          durations:
          - 7
          - 7
          location: location
          formFields:
          - isRequired: true
            name: name
            options:
            - hidden: true
              displayOrder: 9
              doubleData: 3.616076749251911
              description: description
              readOnly: true
              label: label
              value: value
            - hidden: true
              displayOrder: 9
              doubleData: 3.616076749251911
              description: description
              readOnly: true
              label: label
              value: value
            isCustom: true
            label: label
            type: type
            fieldType: fieldType
          - isRequired: true
            name: name
            options:
            - hidden: true
              displayOrder: 9
              doubleData: 3.616076749251911
              description: description
              readOnly: true
              label: label
              value: value
            - hidden: true
              displayOrder: 9
              doubleData: 3.616076749251911
              description: description
              readOnly: true
              label: label
              value: value
            isCustom: true
            label: label
            type: type
            fieldType: fieldType
          legalConsentEnabled: true
          customAvailabilityEndDate: 2
          customAvailabilityStartDate: 4
        linkAvailability:
          hasMore: true
          linkAvailabilityByDuration:
            key:
              meetingDurationMillis: 7
              availabilities:
              - startMillisUtc: 1
                endMillisUtc: 1
              - startMillisUtc: 1
                endMillisUtc: 1
        brandingMetadata:
          logoHeight: 1
          logoAltText: logoAltText
          companyCity: companyCity
          companyAddressLine1: companyAddressLine1
          showSalesAd: true
          companyAddressLine2: companyAddressLine2
          accentColor: accentColor
          companyName: companyName
          companyState: companyState
          primaryColor: primaryColor
          showMarketingAd: true
          accent2Color: accent2Color
          companyDomain: companyDomain
          logoUrl: logoUrl
          logoWidth: 6
          companyCountry: companyCountry
          companyAvatar: companyAvatar
          companyZip: companyZip
          secondaryColor: secondaryColor
        isOffline: true
        linkType: PERSONAL_LINK
        allUsersBusyTimes:
        - meetingsUser:
            isSalesStarter: true
            calendarProvider: calendarProvider
            id: id
            userId: userId
            userProfile:
              firstName: firstName
              lastName: lastName
              fullName: fullName
              email: email
          busyTimes:
          - start: 7
            end: 1
          - start: 7
            end: 1
          isOffline: true
        - meetingsUser:
            isSalesStarter: true
            calendarProvider: calendarProvider
            id: id
            userId: userId
            userProfile:
              firstName: firstName
              lastName: lastName
              fullName: fullName
              email: email
          busyTimes:
          - start: 7
            end: 1
          - start: 7
            end: 1
          isOffline: true
      properties:
        linkId:
          type: string
        customParams:
          $ref: '#/components/schemas/ExternalMeetingsLinkSettings'
        linkAvailability:
          $ref: '#/components/schemas/ExternalLinkAvailability'
        brandingMetadata:
          $ref: '#/components/schemas/ExternalBrandingMetadata'
        isOffline:
          type: boolean
        linkType:
          enum:
          - PERSONAL_LINK
          - GROUP_CALENDAR
          - ROUND_ROBIN_CALENDAR
          type: string
        allUsersBusyTimes:
          items:
            $ref: '#/components/schemas/ExternalUserBusyTimes'
          type: array
      required:
      - allUsersBusyTimes
      - customParams
      - isOffline
      - linkId
      - linkType
      type: object
    ExternalLinkAvailability:
      example:
        hasMore: true
        linkAvailabilityByDuration:
          key:
            meetingDurationMillis: 7
            availabilities:
            - startMillisUtc: 1
              endMillisUtc: 1
            - startMillisUtc: 1
              endMillisUtc: 1
      properties:
        hasMore:
          type: boolean
        linkAvailabilityByDuration:
          additionalProperties:
            $ref: '#/components/schemas/ExternalLinkAvailabilityForDuration'
          type: object
      required:
      - hasMore
      - linkAvailabilityByDuration
      type: object
    ExternalTimeRange:
      example:
        start: 7
        end: 1
      properties:
        start:
          format: int32
          type: integer
        end:
          format: int32
          type: integer
      required:
      - end
      - start
      type: object
    ExternalGuestSettings:
      example:
        maxGuestCount: 0
        canAddGuests: true
      properties:
        maxGuestCount:
          format: int32
          type: integer
        canAddGuests:
          type: boolean
      required:
      - canAddGuests
      - maxGuestCount
      type: object
    ExternalValidatedFormField:
      example:
        translatedLabel: translatedLabel
        valueLabel: valueLabel
        name: name
        isCustom: true
        label: label
        value: value
        fieldType: fieldType
      properties:
        translatedLabel:
          type: string
        valueLabel:
          type: string
        name:
          type: string
        isCustom:
          type: boolean
        label:
          type: string
        value:
          type: string
        fieldType:
          type: string
      required:
      - isCustom
      - label
      - name
      - value
      type: object
    ErrorDetail:
      properties:
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        code:
          description: The status code associated with the error detail
          type: string
        in:
          description: The name of the field or parameter in which the error was found.
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
          type: object
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          type: string
      required:
      - message
      type: object
    ExternalBookingFormField:
      example:
        name: name
        value: value
      properties:
        name:
          type: string
        value:
          type: string
      required:
      - name
      - value
      type: object
    ExternalMeetingsWelcomeScreenInfo:
      example:
        useCompanyLogo: true
        description: description
        showWelcomeScreen: true
        title: title
        logoUrl: logoUrl
      properties:
        useCompanyLogo:
          type: boolean
        description:
          type: string
        showWelcomeScreen:
          type: boolean
        title:
          type: string
        logoUrl:
          type: string
      type: object
    ForwardPaging:
      example:
        next:
          link: link
          after: after
      properties:
        next:
          $ref: '#/components/schemas/NextPage'
      type: object
    ExternalLinkFormField:
      example:
        isRequired: true
        name: name
        options:
        - hidden: true
          displayOrder: 9
          doubleData: 3.616076749251911
          description: description
          readOnly: true
          label: label
          value: value
        - hidden: true
          displayOrder: 9
          doubleData: 3.616076749251911
          description: description
          readOnly: true
          label: label
          value: value
        isCustom: true
        label: label
        type: type
        fieldType: fieldType
      properties:
        isRequired:
          type: boolean
        name:
          type: string
        options:
          items:
            $ref: '#/components/schemas/ExternalOption'
          type: array
        isCustom:
          type: boolean
        label:
          type: string
        type:
          type: string
        fieldType:
          type: string
      required:
      - fieldType
      - isCustom
      - isRequired
      - label
      - name
      - options
      - type
      type: object
    ExternalUserProfile:
      example:
        firstName: firstName
        lastName: lastName
        fullName: fullName
        email: email
      properties:
        firstName:
          type: string
        lastName:
          type: string
        fullName:
          type: string
        email:
          type: string
      required:
      - email
      type: object
    ExternalMeetingsUser:
      example:
        isSalesStarter: true
        calendarProvider: calendarProvider
        id: id
        userId: userId
        userProfile:
          firstName: firstName
          lastName: lastName
          fullName: fullName
          email: email
      properties:
        isSalesStarter:
          type: boolean
        calendarProvider:
          type: string
        id:
          type: string
        userId:
          type: string
        userProfile:
          $ref: '#/components/schemas/ExternalUserProfile'
      required:
      - calendarProvider
      - id
      - isSalesStarter
      - userId
      - userProfile
      type: object
    ExternalBrandingMetadata:
      example:
        logoHeight: 1
        logoAltText: logoAltText
        companyCity: companyCity
        companyAddressLine1: companyAddressLine1
        showSalesAd: true
        companyAddressLine2: companyAddressLine2
        accentColor: accentColor
        companyName: companyName
        companyState: companyState
        primaryColor: primaryColor
        showMarketingAd: true
        accent2Color: accent2Color
        companyDomain: companyDomain
        logoUrl: logoUrl
        logoWidth: 6
        companyCountry: companyCountry
        companyAvatar: companyAvatar
        companyZip: companyZip
        secondaryColor: secondaryColor
      properties:
        logoHeight:
          format: int32
          type: integer
        logoAltText:
          type: string
        companyCity:
          type: string
        companyAddressLine1:
          type: string
        showSalesAd:
          type: boolean
        companyAddressLine2:
          type: string
        accentColor:
          type: string
        companyName:
          type: string
        companyState:
          type: string
        primaryColor:
          type: string
        showMarketingAd:
          type: boolean
        accent2Color:
          type: string
        companyDomain:
          type: string
        logoUrl:
          type: string
        logoWidth:
          format: int32
          type: integer
        companyCountry:
          type: string
        companyAvatar:
          type: string
        companyZip:
          type: string
        secondaryColor:
          type: string
      required:
      - logoAltText
      - showMarketingAd
      - showSalesAd
      type: object
    CollectionResponseWithTotalExternalLinkMetadataForwardPaging:
      example:
        total: 0
        paging:
          next:
            link: link
            after: after
        results:
        - userIdsOfLinkMembers:
          - userIdsOfLinkMembers
          - userIdsOfLinkMembers
          createdAt: 2000-01-23T04:56:07.000+00:00
          link: link
          name: name
          organizerUserId: organizerUserId
          id: id
          defaultLink: true
          type: type
          slug: slug
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - userIdsOfLinkMembers:
          - userIdsOfLinkMembers
          - userIdsOfLinkMembers
          createdAt: 2000-01-23T04:56:07.000+00:00
          link: link
          name: name
          organizerUserId: organizerUserId
          id: id
          defaultLink: true
          type: type
          slug: slug
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        total:
          format: int32
          type: integer
        paging:
          $ref: '#/components/schemas/ForwardPaging'
        results:
          items:
            $ref: '#/components/schemas/ExternalLinkMetadata'
          type: array
      required:
      - results
      - total
      type: object
    Error:
      example:
        message: Invalid input (details will vary based on the error)
        correlationId: aeb5f871-7f07-4993-9211-075dc63e7cbf
        category: VALIDATION_ERROR
        links:
          knowledge-base: https://www.hubspot.com/products/service/knowledge-base
      properties:
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
            invalidPropertyName:
            - propertyValue
          type: object
        correlationId:
          description: A unique identifier for the request. Include this value with
            any error reports or support tickets
          example: aeb5f871-7f07-4993-9211-075dc63e7cbf
          format: uuid
          type: string
        links:
          additionalProperties:
            type: string
          description: A map of link names to associated URIs containing documentation
            about the error or recommended remediation steps
          type: object
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          example: An error occurred
          type: string
        category:
          description: The error category
          type: string
        errors:
          description: further information about the error
          items:
            $ref: '#/components/schemas/ErrorDetail'
          type: array
      required:
      - category
      - correlationId
      - message
      type: object
    ExternalOption:
      example:
        hidden: true
        displayOrder: 9
        doubleData: 3.616076749251911
        description: description
        readOnly: true
        label: label
        value: value
      properties:
        hidden:
          type: boolean
        displayOrder:
          format: int32
          type: integer
        doubleData:
          type: number
        description:
          type: string
        readOnly:
          type: boolean
        label:
          type: string
        value:
          type: string
      required:
      - description
      - displayOrder
      - doubleData
      - hidden
      - label
      - readOnly
      - value
      type: object
    ExternalMeetingBookingResponse:
      example:
        calendarEventId: calendarEventId
        contactId: contactId
        bookingTimezone: bookingTimezone
        legalConsentResponses:
        - communicationTypeId: communicationTypeId
          consented: true
        - communicationTypeId: communicationTypeId
          consented: true
        subject: subject
        start: 2000-01-23T04:56:07.000+00:00
        locale: locale
        webConferenceUrl: webConferenceUrl
        duration: 0
        guestEmails:
        - guestEmails
        - guestEmails
        webConferenceMeetingId: webConferenceMeetingId
        location: location
        isOffline: true
        end: 2000-01-23T04:56:07.000+00:00
        formFields:
        - translatedLabel: translatedLabel
          valueLabel: valueLabel
          name: name
          isCustom: true
          label: label
          value: value
          fieldType: fieldType
        - translatedLabel: translatedLabel
          valueLabel: valueLabel
          name: name
          isCustom: true
          label: label
          value: value
          fieldType: fieldType
      properties:
        calendarEventId:
          type: string
        contactId:
          type: string
        bookingTimezone:
          type: string
        legalConsentResponses:
          items:
            $ref: '#/components/schemas/ExternalLegalConsentResponse'
          type: array
        subject:
          type: string
        start:
          format: date-time
          type: string
        locale:
          type: string
        webConferenceUrl:
          type: string
        duration:
          format: int64
          type: integer
        guestEmails:
          items:
            type: string
          type: array
        webConferenceMeetingId:
          type: string
        location:
          type: string
        isOffline:
          type: boolean
        end:
          format: date-time
          type: string
        formFields:
          items:
            $ref: '#/components/schemas/ExternalValidatedFormField'
          type: array
      required:
      - bookingTimezone
      - calendarEventId
      - contactId
      - duration
      - end
      - formFields
      - guestEmails
      - isOffline
      - legalConsentResponses
      - start
      - subject
      type: object
    ExternalLinkAvailabilityAndBusyTimes:
      example:
        linkAvailability:
          hasMore: true
          linkAvailabilityByDuration:
            key:
              meetingDurationMillis: 7
              availabilities:
              - startMillisUtc: 1
                endMillisUtc: 1
              - startMillisUtc: 1
                endMillisUtc: 1
        allUsersBusyTimes:
        - meetingsUser:
            isSalesStarter: true
            calendarProvider: calendarProvider
            id: id
            userId: userId
            userProfile:
              firstName: firstName
              lastName: lastName
              fullName: fullName
              email: email
          busyTimes:
          - start: 7
            end: 1
          - start: 7
            end: 1
          isOffline: true
        - meetingsUser:
            isSalesStarter: true
            calendarProvider: calendarProvider
            id: id
            userId: userId
            userProfile:
              firstName: firstName
              lastName: lastName
              fullName: fullName
              email: email
          busyTimes:
          - start: 7
            end: 1
          - start: 7
            end: 1
          isOffline: true
      properties:
        linkAvailability:
          $ref: '#/components/schemas/ExternalLinkAvailability'
        allUsersBusyTimes:
          items:
            $ref: '#/components/schemas/ExternalUserBusyTimes'
          type: array
      required:
      - allUsersBusyTimes
      type: object
    ExternalLinkAvailabilityForDuration:
      example:
        meetingDurationMillis: 7
        availabilities:
        - startMillisUtc: 1
          endMillisUtc: 1
        - startMillisUtc: 1
          endMillisUtc: 1
      properties:
        meetingDurationMillis:
          format: int32
          type: integer
        availabilities:
          items:
            $ref: '#/components/schemas/ExternalMeetingAvailability'
          type: array
      required:
      - availabilities
      - meetingDurationMillis
      type: object
    ExternalLinkDisplayInfo:
      example:
        publicDisplayAvatarOption: publicDisplayAvatarOption
        companyAvatar: companyAvatar
        avatar: avatar
        headline: headline
      properties:
        publicDisplayAvatarOption:
          type: string
        companyAvatar:
          type: string
        avatar:
          type: string
        headline:
          type: string
      type: object
    ExternalLegalConsentResponse:
      example:
        communicationTypeId: communicationTypeId
        consented: true
      properties:
        communicationTypeId:
          type: string
        consented:
          type: boolean
      required:
      - communicationTypeId
      - consented
      type: object
    ExternalUserBusyTimes:
      example:
        meetingsUser:
          isSalesStarter: true
          calendarProvider: calendarProvider
          id: id
          userId: userId
          userProfile:
            firstName: firstName
            lastName: lastName
            fullName: fullName
            email: email
        busyTimes:
        - start: 7
          end: 1
        - start: 7
          end: 1
        isOffline: true
      properties:
        meetingsUser:
          $ref: '#/components/schemas/ExternalMeetingsUser'
        busyTimes:
          items:
            $ref: '#/components/schemas/ExternalTimeRange'
          type: array
        isOffline:
          type: boolean
      required:
      - busyTimes
      - isOffline
      - meetingsUser
      type: object
    ExternalLegalConsentOptions:
      example:
        legitimateInterestSubscriptionTypes:
        - 5
        - 5
        processingConsentCheckboxLabel: processingConsentCheckboxLabel
        communicationConsentText: communicationConsentText
        legitimateInterestLegalBasis: LEGITIMATE_INTEREST_PQL
        processingConsentType: processingConsentType
        privacyPolicyText: privacyPolicyText
        processingConsentText: processingConsentText
        communicationConsentCheckboxes:
        - communicationTypeId: communicationTypeId
          label: label
          required: true
        - communicationTypeId: communicationTypeId
          label: label
          required: true
        processingConsentFooterText: processingConsentFooterText
        isLegitimateInterest: true
      properties:
        legitimateInterestSubscriptionTypes:
          items:
            format: int64
            type: integer
          type: array
        processingConsentCheckboxLabel:
          type: string
        communicationConsentText:
          type: string
        legitimateInterestLegalBasis:
          enum:
          - LEGITIMATE_INTEREST_PQL
          - LEGITIMATE_INTEREST_CLIENT
          - PERFORMANCE_OF_CONTRACT
          - CONSENT_WITH_NOTICE
          - NON_GDPR
          - PROCESS_AND_STORE
          - LEGITIMATE_INTEREST_OTHER
          type: string
        processingConsentType:
          type: string
        privacyPolicyText:
          type: string
        processingConsentText:
          type: string
        communicationConsentCheckboxes:
          items:
            $ref: '#/components/schemas/ExternalCommunicationConsentCheckbox'
          type: array
        processingConsentFooterText:
          type: string
        isLegitimateInterest:
          type: boolean
      required:
      - communicationConsentCheckboxes
      - communicationConsentText
      - isLegitimateInterest
      - legitimateInterestSubscriptionTypes
      - privacyPolicyText
      - processingConsentCheckboxLabel
      - processingConsentFooterText
      - processingConsentText
      - processingConsentType
      type: object
    ExternalLinkMetadata:
      example:
        userIdsOfLinkMembers:
        - userIdsOfLinkMembers
        - userIdsOfLinkMembers
        createdAt: 2000-01-23T04:56:07.000+00:00
        link: link
        name: name
        organizerUserId: organizerUserId
        id: id
        defaultLink: true
        type: type
        slug: slug
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        userIdsOfLinkMembers:
          items:
            type: string
          type: array
        createdAt:
          format: date-time
          type: string
        link:
          type: string
        name:
          type: string
        organizerUserId:
          type: string
        id:
          type: string
        defaultLink:
          type: boolean
        type:
          type: string
        slug:
          type: string
        updatedAt:
          format: date-time
          type: string
      required:
      - createdAt
      - defaultLink
      - id
      - link
      - organizerUserId
      - slug
      - type
      - userIdsOfLinkMembers
      type: object
    ExternalCommunicationConsentCheckbox:
      example:
        communicationTypeId: communicationTypeId
        label: label
        required: true
      properties:
        communicationTypeId:
          type: string
        label:
          type: string
        required:
          type: boolean
      required:
      - communicationTypeId
      - label
      - required
      type: object
    NextPage:
      example:
        link: link
        after: after
      properties:
        link:
          type: string
        after:
          type: string
      required:
      - after
      type: object
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            scheduler.meetings.meeting-link.read: Read from meeting links
            crm.schemas.contacts.write: ' '
            crm.objects.goals.write: Write goals
            crm.objects.courses.write: Write courses
            crm.objects.companies.highly_sensitive.write.v2: Change company records
              (highly-sensitive)
            crm.objects.services.write: Write services
            crm.objects.companies.write: ' '
            crm.objects.appointments.sensitive.write.v2: Write appointments (sensitive)
            crm.objects.listings.write: Write listings
            crm.objects.contacts.highly_sensitive.write.v2: Change contact records
              (highly-sensitive)
            crm.objects.deals.sensitive.write.v2: ' '
            crm.objects.contacts.write: ' '
            tickets.highly_sensitive.v2: Tickets (highly-sensitive)
            crm.objects.companies.sensitive.write.v2: ' '
            tickets.sensitive.v2: Tickets (sensitive)
            crm.objects.contacts.sensitive.write.v2: ' '
            crm.objects.line_items.write: Line Items
            crm.objects.appointments.write: Write appointments
            crm.objects.deals.write: ' '
            crm.objects.deals.highly_sensitive.write.v2: Change deal records (highly-sensitive)
            tickets: Read and write tickets
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
