openapi: 3.0.1
info:
  description: ""
  title: Partner Clients
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
  x-hubspot-api-use-case: Sync partner client data with third-party project management
    software.
  x-hubspot-introduction: "Partner clients are HubSpot customers that Solutions Partners\
    \ have a sold or managed relationship with. Use the this API to manage your client\
    \ base as well as sync client data between HubSpot and other systems. Note: you\
    \ can only retrieve and update existing partner clients with this API. This API\
    \ doesn't support creation or deletion."
servers:
- url: https://api.hubapi.com
tags:
- name: Batch
- name: Basic
- name: Search
paths:
  /crm/v3/objects/partner_clients/batch/read:
    post:
      description: 'Retrieve a batch of partner clients by ID (`partnerClientId`)
        or unique property value (`idProperty`). '
      operationId: post-/crm/v3/objects/partner_clients/batch/read
      parameters:
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchReadInputSimplePublicObjectId'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponseSimplePublicObject'
          description: successful operation
        "207":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponseSimplePublicObjectWithErrors'
          description: multiple statuses
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.partner-clients.read
      summary: Retrieve a batch of partner clients
      tags:
      - Batch
  /crm/v3/objects/partner_clients/{partnerClientId}:
    get:
      description: Retrieve a partner client by its ID (`partnerClientId`) or by a
        unique property (`idProperty`). You can specify what is returned using the
        `properties` query parameter.
      operationId: "get-/crm/v3/objects/partner_clients/{partnerClientId}"
      parameters:
      - description: The ID of the partner client to retrieve.
        explode: false
        in: path
        name: partnerClientId
        required: true
        schema:
          type: string
        style: simple
      - description: "A comma separated list of the properties to be returned in the\
          \ response. If any of the specified properties are not present on the requested\
          \ object(s), they will be ignored."
        explode: true
        in: query
        name: properties
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "A comma separated list of the properties to be returned along\
          \ with their history of previous values. If any of the specified properties\
          \ are not present on the requested object(s), they will be ignored."
        explode: true
        in: query
        name: propertiesWithHistory
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "A comma separated list of object types to retrieve associated\
          \ IDs for. If any of the specified associations do not exist, they will\
          \ be ignored."
        explode: true
        in: query
        name: associations
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - description: The name of a property whose values are unique for this object
        explode: true
        in: query
        name: idProperty
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimplePublicObjectWithAssociations'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.partner-clients.read
      summary: Retrieve a partner client
      tags:
      - Basic
    patch:
      description: Update a partner client by ID (`partnerClientId`) or unique property
        value (`idProperty`). Provided property values will be overwritten. Read-only
        and non-existent properties will result in an error. Properties values can
        be cleared by passing an empty string.
      operationId: "patch-/crm/v3/objects/partner_clients/{partnerClientId}"
      parameters:
      - description: The ID of the partner client to update.
        explode: false
        in: path
        name: partnerClientId
        required: true
        schema:
          type: string
        style: simple
      - description: The name of a property whose values are unique for this object
        explode: true
        in: query
        name: idProperty
        required: false
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimplePublicObjectInput'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimplePublicObject'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.partner-clients.write
      - private_apps:
        - crm.objects.partner-clients.write
      summary: Update a partner client
      tags:
      - Basic
  /crm/v3/objects/partner_clients/batch/update:
    post:
      description: Update a batch of partner clients by ID (`partnerClientId`) or
        unique property value (`idProperty`). Provided property values will be overwritten.
        Read-only and non-existent properties will result in an error. Properties
        values can be cleared by passing an empty string.
      operationId: post-/crm/v3/objects/partner_clients/batch/update
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchInputSimplePublicObjectBatchInput'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponseSimplePublicObject'
          description: successful operation
        "207":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponseSimplePublicObjectWithErrors'
          description: multiple statuses
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.partner-clients.write
      - private_apps:
        - crm.objects.partner-clients.write
      summary: Update a batch of partner clients
      tags:
      - Batch
  /crm/v3/objects/partner_clients:
    get:
      description: "Retrieve all partner clients, using query parameters to specify\
        \ the information that gets returned."
      operationId: get-/crm/v3/objects/partner_clients
      parameters:
      - description: The maximum number of results to display per page.
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      - description: The paging cursor token of the last successfully read resource
          will be returned as the `paging.next.after` JSON property of a paged response
          containing more results.
        explode: true
        in: query
        name: after
        required: false
        schema:
          type: string
        style: form
      - description: "A comma separated list of the properties to be returned in the\
          \ response. If any of the specified properties are not present on the requested\
          \ object(s), they will be ignored."
        explode: true
        in: query
        name: properties
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "A comma separated list of the properties to be returned along\
          \ with their history of previous values. If any of the specified properties\
          \ are not present on the requested object(s), they will be ignored. Usage\
          \ of this parameter will reduce the maximum number of objects that can be\
          \ read by a single request."
        explode: true
        in: query
        name: propertiesWithHistory
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "A comma separated list of object types to retrieve associated\
          \ IDs for. If any of the specified associations do not exist, they will\
          \ be ignored."
        explode: true
        in: query
        name: associations
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionResponseSimplePublicObjectWithAssociationsForwardPaging'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.partner-clients.read
      summary: Retrieve partner clients
      tags:
      - Basic
  /crm/v3/objects/partner_clients/search:
    post:
      description: "Search for partner clients by filtering on properties, searching\
        \ through associations, and sorting results. Learn more about [CRM search](https://developers.hubspot.com/docs/guides/api/crm/search#make-a-search-request)."
      operationId: post-/crm/v3/objects/partner_clients/search
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicObjectSearchRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionResponseWithTotalSimplePublicObjectForwardPaging'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.partner-clients.read
      summary: Search for partner clients
      tags:
      - Search
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
components:
  responses:
    Error:
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
      description: An error occurred.
  schemas:
    StandardError:
      example:
        subCategory: "{}"
        context:
          key:
          - context
          - context
        links:
          key: links
        id: id
        category: category
        message: message
        errors:
        - subCategory: subCategory
          code: code
          in: in
          context:
            missingScopes:
            - scope1
            - scope2
          message: message
        - subCategory: subCategory
          code: code
          in: in
          context:
            missingScopes:
            - scope1
            - scope2
          message: message
        status: status
      properties:
        subCategory:
          properties: {}
          type: object
        context:
          additionalProperties:
            items:
              type: string
            type: array
          type: object
        links:
          additionalProperties:
            type: string
          type: object
        id:
          type: string
        category:
          type: string
        message:
          type: string
        errors:
          items:
            $ref: '#/components/schemas/ErrorDetail'
          type: array
        status:
          type: string
      required:
      - category
      - context
      - errors
      - links
      - message
      - status
      type: object
    CollectionResponseAssociatedId:
      example:
        paging:
          next:
            after: NTI1Cg%3D%3D
            link: ?after=NTI1Cg%3D%3D
          prev:
            before: before
            link: link
        results:
        - id: id
          type: type
        - id: id
          type: type
      properties:
        paging:
          $ref: '#/components/schemas/Paging'
        results:
          items:
            $ref: '#/components/schemas/AssociatedId'
          type: array
      required:
      - results
      type: object
    Paging:
      example:
        next:
          after: NTI1Cg%3D%3D
          link: ?after=NTI1Cg%3D%3D
        prev:
          before: before
          link: link
      properties:
        next:
          $ref: '#/components/schemas/NextPage'
        prev:
          $ref: '#/components/schemas/PreviousPage'
      type: object
    PublicObjectSearchRequest:
      example:
        query: query
        limit: 0
        after: after
        sorts:
        - sorts
        - sorts
        properties:
        - properties
        - properties
        filterGroups:
        - filters:
          - highValue: highValue
            propertyName: propertyName
            values:
            - values
            - values
            value: value
            operator: EQ
          - highValue: highValue
            propertyName: propertyName
            values:
            - values
            - values
            value: value
            operator: EQ
        - filters:
          - highValue: highValue
            propertyName: propertyName
            values:
            - values
            - values
            value: value
            operator: EQ
          - highValue: highValue
            propertyName: propertyName
            values:
            - values
            - values
            value: value
            operator: EQ
      properties:
        query:
          type: string
        limit:
          format: int32
          type: integer
        after:
          type: string
        sorts:
          items:
            type: string
          type: array
        properties:
          items:
            type: string
          type: array
        filterGroups:
          items:
            $ref: '#/components/schemas/FilterGroup'
          type: array
      type: object
    Error:
      example:
        message: Invalid input (details will vary based on the error)
        correlationId: aeb5f871-7f07-4993-9211-075dc63e7cbf
        category: VALIDATION_ERROR
        links:
          knowledge-base: https://www.hubspot.com/products/service/knowledge-base
      properties:
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
            invalidPropertyName:
            - propertyValue
          type: object
        correlationId:
          description: A unique identifier for the request. Include this value with
            any error reports or support tickets
          example: aeb5f871-7f07-4993-9211-075dc63e7cbf
          format: uuid
          type: string
        links:
          additionalProperties:
            type: string
          description: A map of link names to associated URIs containing documentation
            about the error or recommended remediation steps
          example:
            knowledge-base: https://www.hubspot.com/products/service/knowledge-base
          type: object
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          example: Invalid input (details will vary based on the error)
          type: string
        category:
          description: The error category
          example: VALIDATION_ERROR
          type: string
        errors:
          description: further information about the error
          items:
            $ref: '#/components/schemas/ErrorDetail'
          type: array
      required:
      - category
      - correlationId
      - message
      type: object
    BatchResponseSimplePublicObject:
      example:
        completedAt: 2000-01-23T04:56:07.000+00:00
        requestedAt: 2000-01-23T04:56:07.000+00:00
        startedAt: 2000-01-23T04:56:07.000+00:00
        links:
          key: links
        results:
        - archived: false
          createdAt: 2019-10-30T03:30:17.883Z
          id: "512"
          properties:
            property_checkbox: "false"
            property_date: "1572480000000"
            property_dropdown: choice_b
            property_multiple_checkboxes: chocolate;strawberry
            property_number: "17"
            property_radio: option_1
            property_string: value
          updatedAt: 2019-12-07T16:50:06.678Z
        - archived: false
          createdAt: 2019-10-30T03:30:17.883Z
          id: "512"
          properties:
            property_checkbox: "false"
            property_date: "1572480000000"
            property_dropdown: choice_b
            property_multiple_checkboxes: chocolate;strawberry
            property_number: "17"
            property_radio: option_1
            property_string: value
          updatedAt: 2019-12-07T16:50:06.678Z
        status: PENDING
      properties:
        completedAt:
          format: date-time
          type: string
        requestedAt:
          format: date-time
          type: string
        startedAt:
          format: date-time
          type: string
        links:
          additionalProperties:
            type: string
          type: object
        results:
          items:
            $ref: '#/components/schemas/SimplePublicObject'
          type: array
        status:
          enum:
          - PENDING
          - PROCESSING
          - CANCELED
          - COMPLETE
          type: string
      required:
      - completedAt
      - results
      - startedAt
      - status
      type: object
    BatchResponseSimplePublicObjectWithErrors:
      example:
        completedAt: 2000-01-23T04:56:07.000+00:00
        numErrors: 0
        requestedAt: 2000-01-23T04:56:07.000+00:00
        startedAt: 2000-01-23T04:56:07.000+00:00
        links:
          key: links
        results:
        - archived: false
          createdAt: 2019-10-30T03:30:17.883Z
          id: "512"
          properties:
            property_checkbox: "false"
            property_date: "1572480000000"
            property_dropdown: choice_b
            property_multiple_checkboxes: chocolate;strawberry
            property_number: "17"
            property_radio: option_1
            property_string: value
          updatedAt: 2019-12-07T16:50:06.678Z
        - archived: false
          createdAt: 2019-10-30T03:30:17.883Z
          id: "512"
          properties:
            property_checkbox: "false"
            property_date: "1572480000000"
            property_dropdown: choice_b
            property_multiple_checkboxes: chocolate;strawberry
            property_number: "17"
            property_radio: option_1
            property_string: value
          updatedAt: 2019-12-07T16:50:06.678Z
        errors:
        - subCategory: "{}"
          context:
            key:
            - context
            - context
          links:
            key: links
          id: id
          category: category
          message: message
          errors:
          - subCategory: subCategory
            code: code
            in: in
            context:
              missingScopes:
              - scope1
              - scope2
            message: message
          - subCategory: subCategory
            code: code
            in: in
            context:
              missingScopes:
              - scope1
              - scope2
            message: message
          status: status
        - subCategory: "{}"
          context:
            key:
            - context
            - context
          links:
            key: links
          id: id
          category: category
          message: message
          errors:
          - subCategory: subCategory
            code: code
            in: in
            context:
              missingScopes:
              - scope1
              - scope2
            message: message
          - subCategory: subCategory
            code: code
            in: in
            context:
              missingScopes:
              - scope1
              - scope2
            message: message
          status: status
        status: PENDING
      properties:
        completedAt:
          format: date-time
          type: string
        numErrors:
          format: int32
          type: integer
        requestedAt:
          format: date-time
          type: string
        startedAt:
          format: date-time
          type: string
        links:
          additionalProperties:
            type: string
          type: object
        results:
          items:
            $ref: '#/components/schemas/SimplePublicObject'
          type: array
        errors:
          items:
            $ref: '#/components/schemas/StandardError'
          type: array
        status:
          enum:
          - PENDING
          - PROCESSING
          - CANCELED
          - COMPLETE
          type: string
      required:
      - completedAt
      - results
      - startedAt
      - status
      type: object
    FilterGroup:
      example:
        filters:
        - highValue: highValue
          propertyName: propertyName
          values:
          - values
          - values
          value: value
          operator: EQ
        - highValue: highValue
          propertyName: propertyName
          values:
          - values
          - values
          value: value
          operator: EQ
      properties:
        filters:
          items:
            $ref: '#/components/schemas/Filter'
          type: array
      required:
      - filters
      type: object
    SimplePublicObjectInput:
      example:
        properties:
          property_checkbox: "false"
          property_date: "1572480000000"
          property_dropdown: choice_b
          property_multiple_checkboxes: chocolate;strawberry
          property_number: "17"
          property_radio: option_1
          property_string: value
      properties:
        properties:
          additionalProperties:
            type: string
          example:
            property_date: "1572480000000"
            property_radio: option_1
            property_number: "17"
            property_string: value
            property_checkbox: "false"
            property_dropdown: choice_b
            property_multiple_checkboxes: chocolate;strawberry
          type: object
      required:
      - properties
      type: object
    ErrorDetail:
      example:
        subCategory: subCategory
        code: code
        in: in
        context:
          missingScopes:
          - scope1
          - scope2
        message: message
      properties:
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        code:
          description: The status code associated with the error detail
          type: string
        in:
          description: The name of the field or parameter in which the error was found.
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
          type: object
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          type: string
      required:
      - message
      type: object
    CollectionResponseSimplePublicObjectWithAssociationsForwardPaging:
      example:
        paging:
          next:
            after: NTI1Cg%3D%3D
            link: ?after=NTI1Cg%3D%3D
        results:
        - associations:
            key:
              paging:
                next:
                  after: NTI1Cg%3D%3D
                  link: ?after=NTI1Cg%3D%3D
                prev:
                  before: before
                  link: link
              results:
              - id: id
                type: type
              - id: id
                type: type
          createdAt: 2000-01-23T04:56:07.000+00:00
          archived: true
          archivedAt: 2000-01-23T04:56:07.000+00:00
          propertiesWithHistory:
            key:
            - sourceId: sourceId
              sourceType: sourceType
              sourceLabel: sourceLabel
              updatedByUserId: 0
              value: value
              timestamp: 2000-01-23T04:56:07.000+00:00
            - sourceId: sourceId
              sourceType: sourceType
              sourceLabel: sourceLabel
              updatedByUserId: 0
              value: value
              timestamp: 2000-01-23T04:56:07.000+00:00
          id: id
          objectWriteTraceId: objectWriteTraceId
          properties:
            key: properties
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - associations:
            key:
              paging:
                next:
                  after: NTI1Cg%3D%3D
                  link: ?after=NTI1Cg%3D%3D
                prev:
                  before: before
                  link: link
              results:
              - id: id
                type: type
              - id: id
                type: type
          createdAt: 2000-01-23T04:56:07.000+00:00
          archived: true
          archivedAt: 2000-01-23T04:56:07.000+00:00
          propertiesWithHistory:
            key:
            - sourceId: sourceId
              sourceType: sourceType
              sourceLabel: sourceLabel
              updatedByUserId: 0
              value: value
              timestamp: 2000-01-23T04:56:07.000+00:00
            - sourceId: sourceId
              sourceType: sourceType
              sourceLabel: sourceLabel
              updatedByUserId: 0
              value: value
              timestamp: 2000-01-23T04:56:07.000+00:00
          id: id
          objectWriteTraceId: objectWriteTraceId
          properties:
            key: properties
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        paging:
          $ref: '#/components/schemas/ForwardPaging'
        results:
          items:
            $ref: '#/components/schemas/SimplePublicObjectWithAssociations'
          type: array
      required:
      - results
      type: object
    ForwardPaging:
      example:
        next:
          after: NTI1Cg%3D%3D
          link: ?after=NTI1Cg%3D%3D
      properties:
        next:
          $ref: '#/components/schemas/NextPage'
      type: object
    SimplePublicObjectId:
      example:
        id: id
      properties:
        id:
          type: string
      required:
      - id
      type: object
    SimplePublicObjectWithAssociations:
      example:
        associations:
          key:
            paging:
              next:
                after: NTI1Cg%3D%3D
                link: ?after=NTI1Cg%3D%3D
              prev:
                before: before
                link: link
            results:
            - id: id
              type: type
            - id: id
              type: type
        createdAt: 2000-01-23T04:56:07.000+00:00
        archived: true
        archivedAt: 2000-01-23T04:56:07.000+00:00
        propertiesWithHistory:
          key:
          - sourceId: sourceId
            sourceType: sourceType
            sourceLabel: sourceLabel
            updatedByUserId: 0
            value: value
            timestamp: 2000-01-23T04:56:07.000+00:00
          - sourceId: sourceId
            sourceType: sourceType
            sourceLabel: sourceLabel
            updatedByUserId: 0
            value: value
            timestamp: 2000-01-23T04:56:07.000+00:00
        id: id
        objectWriteTraceId: objectWriteTraceId
        properties:
          key: properties
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        associations:
          additionalProperties:
            $ref: '#/components/schemas/CollectionResponseAssociatedId'
          type: object
        createdAt:
          format: date-time
          type: string
        archived:
          type: boolean
        archivedAt:
          format: date-time
          type: string
        propertiesWithHistory:
          additionalProperties:
            items:
              $ref: '#/components/schemas/ValueWithTimestamp'
            type: array
          type: object
        id:
          type: string
        objectWriteTraceId:
          type: string
        properties:
          additionalProperties:
            nullable: true
            type: string
          type: object
        updatedAt:
          format: date-time
          type: string
      required:
      - createdAt
      - id
      - properties
      - updatedAt
      type: object
    BatchReadInputSimplePublicObjectId:
      example:
        propertiesWithHistory:
        - propertiesWithHistory
        - propertiesWithHistory
        idProperty: idProperty
        inputs:
        - id: id
        - id: id
        properties:
        - properties
        - properties
      properties:
        propertiesWithHistory:
          items:
            type: string
          type: array
        idProperty:
          description: "When using a custom unique value property to retrieve records,\
            \ the name of the property. Do not include this parameter if retrieving\
            \ by record ID."
          type: string
        inputs:
          items:
            $ref: '#/components/schemas/SimplePublicObjectId'
          type: array
        properties:
          items:
            type: string
          type: array
      required:
      - inputs
      - properties
      - propertiesWithHistory
      type: object
    Filter:
      example:
        highValue: highValue
        propertyName: propertyName
        values:
        - values
        - values
        value: value
        operator: EQ
      properties:
        highValue:
          type: string
        propertyName:
          type: string
        values:
          items:
            type: string
          type: array
        value:
          type: string
        operator:
          description: "null"
          enum:
          - EQ
          - NEQ
          - LT
          - LTE
          - GT
          - GTE
          - BETWEEN
          - IN
          - NOT_IN
          - HAS_PROPERTY
          - NOT_HAS_PROPERTY
          - CONTAINS_TOKEN
          - NOT_CONTAINS_TOKEN
          type: string
      required:
      - operator
      - propertyName
      type: object
    BatchInputSimplePublicObjectBatchInput:
      example:
        inputs:
        - idProperty: my_unique_property_name
          objectWriteTraceId: objectWriteTraceId
          id: id
          properties:
            key: properties
        - idProperty: my_unique_property_name
          objectWriteTraceId: objectWriteTraceId
          id: id
          properties:
            key: properties
      properties:
        inputs:
          items:
            $ref: '#/components/schemas/SimplePublicObjectBatchInput'
          type: array
      required:
      - inputs
      type: object
    PreviousPage:
      example:
        before: before
        link: link
      properties:
        before:
          type: string
        link:
          type: string
      required:
      - before
      type: object
    ValueWithTimestamp:
      example:
        sourceId: sourceId
        sourceType: sourceType
        sourceLabel: sourceLabel
        updatedByUserId: 0
        value: value
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        sourceId:
          type: string
        sourceType:
          type: string
        sourceLabel:
          type: string
        updatedByUserId:
          format: int32
          type: integer
        value:
          type: string
        timestamp:
          format: date-time
          type: string
      required:
      - sourceType
      - timestamp
      - value
      type: object
    SimplePublicObjectBatchInput:
      example:
        idProperty: my_unique_property_name
        objectWriteTraceId: objectWriteTraceId
        id: id
        properties:
          key: properties
      properties:
        idProperty:
          description: The name of a property whose values are unique for this object
          example: my_unique_property_name
          type: string
        objectWriteTraceId:
          type: string
        id:
          description: "The id to be updated. This can be the object id, or the unique\
            \ property value of the idProperty property"
          type: string
        properties:
          additionalProperties:
            type: string
          type: object
      required:
      - id
      - properties
      type: object
    AssociatedId:
      example:
        id: id
        type: type
      properties:
        id:
          type: string
        type:
          type: string
      required:
      - id
      - type
      type: object
    CollectionResponseWithTotalSimplePublicObjectForwardPaging:
      example:
        total: 0
        paging:
          next:
            after: NTI1Cg%3D%3D
            link: ?after=NTI1Cg%3D%3D
        results:
        - archived: false
          createdAt: 2019-10-30T03:30:17.883Z
          id: "512"
          properties:
            property_checkbox: "false"
            property_date: "1572480000000"
            property_dropdown: choice_b
            property_multiple_checkboxes: chocolate;strawberry
            property_number: "17"
            property_radio: option_1
            property_string: value
          updatedAt: 2019-12-07T16:50:06.678Z
        - archived: false
          createdAt: 2019-10-30T03:30:17.883Z
          id: "512"
          properties:
            property_checkbox: "false"
            property_date: "1572480000000"
            property_dropdown: choice_b
            property_multiple_checkboxes: chocolate;strawberry
            property_number: "17"
            property_radio: option_1
            property_string: value
          updatedAt: 2019-12-07T16:50:06.678Z
      properties:
        total:
          format: int32
          type: integer
        paging:
          $ref: '#/components/schemas/ForwardPaging'
        results:
          items:
            $ref: '#/components/schemas/SimplePublicObject'
          type: array
      required:
      - results
      - total
      type: object
    NextPage:
      example:
        after: NTI1Cg%3D%3D
        link: ?after=NTI1Cg%3D%3D
      properties:
        link:
          example: ?after=NTI1Cg%3D%3D
          type: string
        after:
          example: NTI1Cg%3D%3D
          type: string
      required:
      - after
      type: object
    SimplePublicObject:
      example:
        archived: false
        createdAt: 2019-10-30T03:30:17.883Z
        id: "512"
        properties:
          property_checkbox: "false"
          property_date: "1572480000000"
          property_dropdown: choice_b
          property_multiple_checkboxes: chocolate;strawberry
          property_number: "17"
          property_radio: option_1
          property_string: value
        updatedAt: 2019-12-07T16:50:06.678Z
      properties:
        createdAt:
          format: date-time
          type: string
        archived:
          example: false
          type: boolean
        archivedAt:
          format: date-time
          type: string
        propertiesWithHistory:
          additionalProperties:
            items:
              $ref: '#/components/schemas/ValueWithTimestamp'
            type: array
          type: object
        id:
          example: "512"
          type: string
        objectWriteTraceId:
          type: string
        properties:
          additionalProperties:
            nullable: true
            type: string
          example:
            property_date: "1572480000000"
            property_radio: option_1
            property_number: "17"
            property_string: value
            property_checkbox: "false"
            property_dropdown: choice_b
            property_multiple_checkboxes: chocolate;strawberry
          type: object
        updatedAt:
          format: date-time
          type: string
      required:
      - createdAt
      - id
      - properties
      - updatedAt
      type: object
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.contacts.highly_sensitive.read.v2: View contact records (highly-sensitive)
            crm.objects.appointments.read: Read appointments
            crm.objects.orders.write: Write orders
            crm.objects.custom.sensitive.write.v2: Change custom object records (sensitive)
            crm.objects.carts.read: Read carts
            tickets.highly_sensitive.v2: Tickets (highly-sensitive)
            crm.objects.users.write: Write User CRM objects
            crm.objects.services.write: Write services
            crm.objects.contacts.highly_sensitive.write.v2: Change contact records
              (highly-sensitive)
            crm.objects.partner-clients.write: Modify Partner Client CRM objects
            crm.objects.custom.write: Change custom object records
            crm.objects.quotes.read: Quotes
            crm.objects.contacts.sensitive.read.v2: ' '
            crm.objects.custom.highly_sensitive.read.v2: View custom object records
              (highly-sensitive)
            crm.objects.goals.write: Write goals
            crm.objects.custom.sensitive.read.v2: View custom object records (sensitive)
            tickets.sensitive.v2: Tickets (sensitive)
            crm.objects.appointments.sensitive.read.v2: Read appointments (sensitive)
            crm.objects.contacts.sensitive.write.v2: ' '
            crm.objects.companies.highly_sensitive.write.v2: Change company records
              (highly-sensitive)
            crm.objects.partner-clients.read: View Partner Client CRM objects
            crm.objects.deals.write: ' '
            crm.objects.leads.write: Modify lead objects
            crm.objects.companies.read: ' '
            crm.objects.listings.read: Read listings
            crm.objects.deals.highly_sensitive.read.v2: View deal records (highly-sensitive)
            crm.objects.contacts.write: ' '
            crm.objects.carts.write: Write cart
            crm.objects.companies.sensitive.read.v2: ' '
            crm.objects.invoices.read: Read invoices objects
            crm.objects.subscriptions.read: Read Commerce Subscriptions
            crm.objects.invoices.write: Write invoices
            crm.objects.deals.highly_sensitive.write.v2: Change deal records (highly-sensitive)
            crm.objects.goals.read: Read goals
            crm.objects.custom.highly_sensitive.write.v2: Change custom object records
              (highly-sensitive)
            crm.objects.commercepayments.read: Read the COMMERCE_PAYMENT object.
            crm.objects.deals.sensitive.write.v2: ' '
            crm.objects.appointments.write: Write appointments
            media_bridge.read: Read media and media events
            crm.objects.line_items.write: Line Items
            crm.objects.orders.read: Read Orders
            crm.objects.subscriptions.write: Write to Commerce Subscriptions
            crm.objects.contacts.read: ' '
            crm.objects.courses.read: Read courses
            crm.objects.quotes.write: Quotes
            crm.objects.deals.sensitive.read.v2: ' '
            crm.objects.line_items.read: Line Items
            crm.objects.users.read: Read User CRM objects
            tickets: Read and write tickets
            crm.objects.companies.sensitive.write.v2: ' '
            crm.objects.leads.read: Read lead objects
            crm.objects.services.read: Read services
            crm.objects.courses.write: Write courses
            crm.objects.custom.read: View custom object records
            crm.objects.listings.write: Write listings
            crm.objects.companies.write: ' '
            crm.objects.appointments.sensitive.write.v2: Write appointments (sensitive)
            crm.objects.deals.read: ' '
            crm.objects.companies.highly_sensitive.read.v2: View company records (highly-sensitive)
            e-commerce: e-commerce
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
