openapi: 3.0.1
info:
  description: '"Use these endpoints for interacting with Blog objects"'
  title: Blog Settings
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: PROFESSIONAL
    sales: FREE
    service: FREE
    cms: STARTER
servers:
- url: https://api.hubapi.com
tags:
- name: Blogs
paths:
  /cms/v3/blog-settings/settings/multi-language/update-languages:
    post:
      description: Explicitly set new languages for each blog in a multi-language
        group.
      operationId: post-/cms/v3/blog-settings/settings/multi-language/update-languages
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLanguagesRequestVNext'
        description: The JSON representation of the UpdateLanguagesRequest object.
        required: true
      responses:
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
        "200":
          content: {}
          description: successful operation
      security:
      - oauth2:
        - content
      - private_apps:
        - content
      summary: Update languages of multi-language group
      tags:
      - Blogs
  /cms/v3/blog-settings/settings/{blogId}/revisions:
    get:
      description: Retrieves all the previous versions of a Blog
      operationId: "get-/cms/v3/blog-settings/settings/{blogId}/revisions"
      parameters:
      - description: The Blog id.
        explode: false
        in: path
        name: blogId
        required: true
        schema:
          type: string
        style: simple
      - description: The cursor token value to get the next set of results. You can
          get this from the `paging.next.after` JSON property of a paged response
          containing more results.
        explode: true
        in: query
        name: after
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: before
        required: false
        schema:
          type: string
        style: form
      - description: The maximum number of results to return. Default is 100.
        explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionResponseWithTotalVersionBlog'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - content
      - private_apps:
        - content
      summary: Retrieves all the previous versions of a Blog
      tags:
      - Blogs
  /cms/v3/blog-settings/settings/{blogId}/revisions/{revisionId}:
    get:
      description: Retrieves a previous version of a Blog
      operationId: "get-/cms/v3/blog-settings/settings/{blogId}/revisions/{revisionId}"
      parameters:
      - description: The Blog id.
        explode: false
        in: path
        name: blogId
        required: true
        schema:
          type: string
        style: simple
      - description: The Blog version id.
        explode: false
        in: path
        name: revisionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionBlog'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - content
      - private_apps:
        - content
      summary: Retrieves a previous version of a Blog
      tags:
      - Blogs
  /cms/v3/blog-settings/settings/{blogId}:
    get:
      description: Retrieve the Blog object identified by the id in the path.
      operationId: "get-/cms/v3/blog-settings/settings/{blogId}"
      parameters:
      - description: The Blog id.
        explode: false
        in: path
        name: blogId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - content
      - private_apps:
        - content
      summary: Retrieve a Blog
      tags:
      - Blogs
  /cms/v3/blog-settings/settings/multi-language/create-language-variation:
    post:
      description: Create a new language variation from an existing blog
      operationId: post-/cms/v3/blog-settings/settings/multi-language/create-language-variation
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlogLanguageCloneRequestVNext'
        description: The JSON representation of the ContentLanguageCloneRequest object.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - content
      - private_apps:
        - content
      summary: Create a new language variation
      tags:
      - Blogs
  /cms/v3/blog-settings/settings:
    get:
      description: |
        Get the list of Blogs. Supports paging and filtering. This method would be useful for an integration that examined these models and used an external service to suggest edits.
      operationId: get-/cms/v3/blog-settings/settings
      parameters:
      - description: Only return Blogs created at exactly the specified time.
        explode: true
        in: query
        name: createdAt
        required: false
        schema:
          format: date-time
          type: string
        style: form
      - description: Only return Blogs created after the specified time.
        explode: true
        in: query
        name: createdAfter
        required: false
        schema:
          format: date-time
          type: string
        style: form
      - description: Only return Blogs created before the specified time.
        explode: true
        in: query
        name: createdBefore
        required: false
        schema:
          format: date-time
          type: string
        style: form
      - description: Only return Blogs last updated at exactly the specified time.
        explode: true
        in: query
        name: updatedAt
        required: false
        schema:
          format: date-time
          type: string
        style: form
      - description: Only return Blogs last updated after the specified time.
        explode: true
        in: query
        name: updatedAfter
        required: false
        schema:
          format: date-time
          type: string
        style: form
      - description: Only return Blogs last updated before the specified time.
        explode: true
        in: query
        name: updatedBefore
        required: false
        schema:
          format: date-time
          type: string
        style: form
      - description: Specifies which fields to use for sorting results. Valid fields
          are `name` and `id`
        explode: true
        in: query
        name: sort
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: The cursor token value to get the next set of results. You can
          get this from the `paging.next.after` JSON property of a paged response
          containing more results.
        explode: true
        in: query
        name: after
        required: false
        schema:
          type: string
        style: form
      - description: The maximum number of results to return. Default is 100.
        explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - description: Specifies whether to return archived Blogs. Defaults to `false`.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionResponseWithTotalBlogForwardPaging'
          description: successful operation
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - content
      - private_apps:
        - content
      summary: Get all Blogs
      tags:
      - Blogs
  /cms/v3/blog-settings/settings/multi-language/set-new-lang-primary:
    put:
      description: Set a blog as the primary language of a multi-language group.
      operationId: put-/cms/v3/blog-settings/settings/multi-language/set-new-lang-primary
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetNewLanguagePrimaryRequestVNext'
        description: The JSON representation of the SetNewLanguagePrimaryRequest object.
        required: true
      responses:
        "204":
          content: {}
          description: No content
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
      security:
      - oauth2:
        - content
      - private_apps:
        - content
      summary: Set a new primary language
      tags:
      - Blogs
  /cms/v3/blog-settings/settings/multi-language/detach-from-lang-group:
    post:
      description: Detach a blog from a multi-language group.
      operationId: post-/cms/v3/blog-settings/settings/multi-language/detach-from-lang-group
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetachFromLangGroupRequestVNext'
        description: The JSON representation of the DetachFromLangGroupRequest object.
        required: true
      responses:
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
        "200":
          content: {}
          description: successful operation
      security:
      - oauth2:
        - content
      - private_apps:
        - content
      summary: Detach a blog from a multi-language group
      tags:
      - Blogs
  /cms/v3/blog-settings/settings/multi-language/attach-to-lang-group:
    post:
      description: Attach a blog to a multi-language group.
      operationId: post-/cms/v3/blog-settings/settings/multi-language/attach-to-lang-group
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AttachToLangPrimaryRequestVNext'
        description: The JSON representation of the AttachToLangPrimaryRequest object.
        required: true
      responses:
        default:
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Error'
          description: An error occurred.
        "200":
          content: {}
          description: successful operation
      security:
      - oauth2:
        - content
      - private_apps:
        - content
      summary: Attach a blog to a multi-language group
      tags:
      - Blogs
components:
  responses:
    Error:
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/Error'
      description: An error occurred.
  schemas:
    UpdateLanguagesRequestVNext:
      description: Request object for updating languages within a multi-language group.
      example:
        languages:
          key: languages
        primaryId: primaryId
      properties:
        languages:
          additionalProperties:
            type: string
          description: Map of object IDs to associated languages of object in the
            multi-language group.
          type: object
        primaryId:
          description: ID of the primary object in the multi-language group.
          type: string
      required:
      - languages
      - primaryId
      type: object
    SetNewLanguagePrimaryRequestVNext:
      description: Request body object for setting a new primary language.
      example:
        id: id
      properties:
        id:
          description: ID of object to set as primary in multi-language group.
          type: string
      required:
      - id
      type: object
    DetachFromLangGroupRequestVNext:
      description: Request body object for detaching objects from multi-language groups.
      example:
        id: id
      properties:
        id:
          description: ID of the object to remove from a multi-language group.
          type: string
      required:
      - id
      type: object
    Paging:
      description: Model definition for paging.
      example:
        next:
          link: link
          after: after
        prev:
          before: before
          link: link
      properties:
        next:
          $ref: '#/components/schemas/NextPage'
        prev:
          $ref: '#/components/schemas/PreviousPage'
      type: object
    Error:
      example:
        message: Invalid input (details will vary based on the error)
        correlationId: aeb5f871-7f07-4993-9211-075dc63e7cbf
        category: VALIDATION_ERROR
        links:
          knowledge-base: https://www.hubspot.com/products/service/knowledge-base
      properties:
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
            invalidPropertyName:
            - propertyValue
          type: object
        correlationId:
          description: A unique identifier for the request. Include this value with
            any error reports or support tickets
          example: aeb5f871-7f07-4993-9211-075dc63e7cbf
          format: uuid
          type: string
        links:
          additionalProperties:
            type: string
          description: A map of link names to associated URIs containing documentation
            about the error or recommended remediation steps
          example:
            knowledge-base: https://www.hubspot.com/products/service/knowledge-base
          type: object
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          example: Invalid input (details will vary based on the error)
          type: string
        category:
          description: The error category
          example: VALIDATION_ERROR
          type: string
        errors:
          description: further information about the error
          items:
            $ref: '#/components/schemas/ErrorDetail'
          type: array
      required:
      - category
      - correlationId
      - message
      type: object
    AttachToLangPrimaryRequestVNext:
      description: Request body object for attaching objects to multi-language groups.
      example:
        language: language
        id: id
        primaryId: primaryId
        primaryLanguage: primaryLanguage
      properties:
        language:
          description: Designated language of the object to add to a multi-language
            group.
          type: string
        id:
          description: ID of the object to add to a multi-language group.
          type: string
        primaryId:
          description: ID of primary language object in multi-language group.
          type: string
        primaryLanguage:
          description: Primary language of the multi-language group.
          type: string
      required:
      - id
      - language
      - primaryId
      type: object
    VersionBlog:
      description: Model definition for a Version Blog. Contains metadata describing
        the version of the Blog. It can be used to view edit history of the settings.
      example:
        id: id
        user:
          fullName: fullName
          id: id
          email: email
        object:
          created: 2000-01-23T04:56:07.000+00:00
          absoluteUrl: absoluteUrl
          description: description
          language: af
          translatedFromId: translatedFromId
          publicAccessRules:
          - {}
          - {}
          publicTitle: publicTitle
          allowComments: true
          deletedAt: 2000-01-23T04:56:07.000+00:00
          htmlTitle: htmlTitle
          publicAccessRulesEnabled: true
          name: name
          id: id
          updated: 2000-01-23T04:56:07.000+00:00
          slug: slug
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          description: The id of the version.
          type: string
        user:
          $ref: '#/components/schemas/VersionUser'
        object:
          $ref: '#/components/schemas/Blog'
        updatedAt:
          format: date-time
          type: string
      required:
      - id
      - object
      - updatedAt
      - user
      type: object
    ErrorDetail:
      properties:
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        code:
          description: The status code associated with the error detail
          type: string
        in:
          description: The name of the field or parameter in which the error was found.
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
          type: object
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          type: string
      required:
      - message
      type: object
    PublicAccessRule:
      example: {}
      properties: {}
      type: object
    ForwardPaging:
      description: Model definition for forward paging.
      example:
        next:
          link: link
          after: after
      properties:
        next:
          $ref: '#/components/schemas/NextPage'
      type: object
    PreviousPage:
      description: Model definition for a previous page
      example:
        before: before
        link: link
      properties:
        before:
          description: ""
          type: string
        link:
          description: ""
          type: string
      required:
      - before
      type: object
    BlogLanguageCloneRequestVNext:
      description: Request body object for creating new language variant blog.
      example:
        language: language
        id: id
        primaryLanguage: primaryLanguage
        slug: slug
      properties:
        language:
          description: Target language of new variant.
          type: string
        id:
          description: ID of blog to clone.
          type: string
        primaryLanguage:
          description: Language of primary blog to clone.
          type: string
        slug:
          description: Path to this blog.
          type: string
      required:
      - id
      type: object
    CollectionResponseWithTotalBlogForwardPaging:
      description: Response object for collections of blogs with pagination information.
      example:
        total: 0
        paging:
          next:
            link: link
            after: after
        results:
        - created: 2000-01-23T04:56:07.000+00:00
          absoluteUrl: absoluteUrl
          description: description
          language: af
          translatedFromId: translatedFromId
          publicAccessRules:
          - {}
          - {}
          publicTitle: publicTitle
          allowComments: true
          deletedAt: 2000-01-23T04:56:07.000+00:00
          htmlTitle: htmlTitle
          publicAccessRulesEnabled: true
          name: name
          id: id
          updated: 2000-01-23T04:56:07.000+00:00
          slug: slug
        - created: 2000-01-23T04:56:07.000+00:00
          absoluteUrl: absoluteUrl
          description: description
          language: af
          translatedFromId: translatedFromId
          publicAccessRules:
          - {}
          - {}
          publicTitle: publicTitle
          allowComments: true
          deletedAt: 2000-01-23T04:56:07.000+00:00
          htmlTitle: htmlTitle
          publicAccessRulesEnabled: true
          name: name
          id: id
          updated: 2000-01-23T04:56:07.000+00:00
          slug: slug
      properties:
        total:
          description: Total number of blogs.
          format: int32
          type: integer
        paging:
          $ref: '#/components/schemas/ForwardPaging'
        results:
          description: Collection of blogs.
          items:
            $ref: '#/components/schemas/Blog'
          type: array
      required:
      - results
      - total
      type: object
    CollectionResponseWithTotalVersionBlog:
      description: Response object for collections of blog versions with pagination
        information.
      example:
        total: 0
        paging:
          next:
            link: link
            after: after
          prev:
            before: before
            link: link
        results:
        - id: id
          user:
            fullName: fullName
            id: id
            email: email
          object:
            created: 2000-01-23T04:56:07.000+00:00
            absoluteUrl: absoluteUrl
            description: description
            language: af
            translatedFromId: translatedFromId
            publicAccessRules:
            - {}
            - {}
            publicTitle: publicTitle
            allowComments: true
            deletedAt: 2000-01-23T04:56:07.000+00:00
            htmlTitle: htmlTitle
            publicAccessRulesEnabled: true
            name: name
            id: id
            updated: 2000-01-23T04:56:07.000+00:00
            slug: slug
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - id: id
          user:
            fullName: fullName
            id: id
            email: email
          object:
            created: 2000-01-23T04:56:07.000+00:00
            absoluteUrl: absoluteUrl
            description: description
            language: af
            translatedFromId: translatedFromId
            publicAccessRules:
            - {}
            - {}
            publicTitle: publicTitle
            allowComments: true
            deletedAt: 2000-01-23T04:56:07.000+00:00
            htmlTitle: htmlTitle
            publicAccessRulesEnabled: true
            name: name
            id: id
            updated: 2000-01-23T04:56:07.000+00:00
            slug: slug
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        total:
          description: Total number of blog versions.
          format: int32
          type: integer
        paging:
          $ref: '#/components/schemas/Paging'
        results:
          description: Collection of blog versions.
          items:
            $ref: '#/components/schemas/VersionBlog'
          type: array
      required:
      - results
      - total
      type: object
    Blog:
      example:
        created: 2000-01-23T04:56:07.000+00:00
        absoluteUrl: absoluteUrl
        description: description
        language: af
        translatedFromId: translatedFromId
        publicAccessRules:
        - {}
        - {}
        publicTitle: publicTitle
        allowComments: true
        deletedAt: 2000-01-23T04:56:07.000+00:00
        htmlTitle: htmlTitle
        publicAccessRulesEnabled: true
        name: name
        id: id
        updated: 2000-01-23T04:56:07.000+00:00
        slug: slug
      properties:
        created:
          format: date-time
          type: string
        absoluteUrl:
          type: string
        description:
          description: The Description of this Blog.
          type: string
        language:
          description: "The explicitly defined language of the Blog. If null, the\
            \ Blog will default to the language of the Domain."
          enum:
          - af
          - af-na
          - af-za
          - agq
          - agq-cm
          - ak
          - ak-gh
          - am
          - am-et
          - ar
          - ar-001
          - ar-ae
          - ar-bh
          - ar-dj
          - ar-dz
          - ar-eg
          - ar-eh
          - ar-er
          - ar-il
          - ar-iq
          - ar-jo
          - ar-km
          - ar-kw
          - ar-lb
          - ar-ly
          - ar-ma
          - ar-mr
          - ar-om
          - ar-ps
          - ar-qa
          - ar-sa
          - ar-sd
          - ar-so
          - ar-ss
          - ar-sy
          - ar-td
          - ar-tn
          - ar-ye
          - as
          - as-in
          - asa
          - asa-tz
          - ast
          - ast-es
          - az
          - az-az
          - bas
          - bas-cm
          - be
          - be-by
          - bem
          - bem-zm
          - bez
          - bez-tz
          - bg
          - bg-bg
          - bm
          - bm-ml
          - bn
          - bn-bd
          - bn-in
          - bo
          - bo-cn
          - bo-in
          - br
          - br-fr
          - brx
          - brx-in
          - bs
          - bs-ba
          - ca
          - ca-ad
          - ca-es
          - ca-fr
          - ca-it
          - ccp
          - ccp-bd
          - ccp-in
          - ce
          - ce-ru
          - ceb
          - ceb-ph
          - cgg
          - cgg-ug
          - chr
          - chr-us
          - ckb
          - ckb-iq
          - ckb-ir
          - cs
          - cs-cz
          - cu
          - cu-ru
          - cy
          - cy-gb
          - da
          - da-dk
          - da-gl
          - dav
          - dav-ke
          - de
          - de-at
          - de-be
          - de-ch
          - de-de
          - de-gr
          - de-it
          - de-li
          - de-lu
          - dje
          - dje-ne
          - doi
          - doi-in
          - dsb
          - dsb-de
          - dua
          - dua-cm
          - dyo
          - dyo-sn
          - dz
          - dz-bt
          - ebu
          - ebu-ke
          - ee
          - ee-gh
          - ee-tg
          - el
          - el-cy
          - el-gr
          - en
          - en-001
          - en-150
          - en-ae
          - en-ag
          - en-ai
          - en-as
          - en-at
          - en-au
          - en-bb
          - en-be
          - en-bi
          - en-bm
          - en-bs
          - en-bw
          - en-bz
          - en-ca
          - en-cc
          - en-ch
          - en-ck
          - en-cm
          - en-cn
          - en-cx
          - en-cy
          - en-de
          - en-dg
          - en-dk
          - en-dm
          - en-er
          - en-fi
          - en-fj
          - en-fk
          - en-fm
          - en-gb
          - en-gd
          - en-gg
          - en-gh
          - en-gi
          - en-gm
          - en-gu
          - en-gy
          - en-hk
          - en-ie
          - en-il
          - en-im
          - en-in
          - en-io
          - en-je
          - en-jm
          - en-ke
          - en-ki
          - en-kn
          - en-ky
          - en-lc
          - en-lr
          - en-ls
          - en-lu
          - en-mg
          - en-mh
          - en-mo
          - en-mp
          - en-ms
          - en-mt
          - en-mu
          - en-mw
          - en-mx
          - en-my
          - en-na
          - en-nf
          - en-ng
          - en-nl
          - en-nr
          - en-nu
          - en-nz
          - en-pg
          - en-ph
          - en-pk
          - en-pn
          - en-pr
          - en-pw
          - en-rw
          - en-sb
          - en-sc
          - en-sd
          - en-se
          - en-sg
          - en-sh
          - en-si
          - en-sl
          - en-ss
          - en-sx
          - en-sz
          - en-tc
          - en-tk
          - en-to
          - en-tt
          - en-tv
          - en-tz
          - en-ug
          - en-um
          - en-us
          - en-vc
          - en-vg
          - en-vi
          - en-vu
          - en-ws
          - en-za
          - en-zm
          - en-zw
          - eo
          - eo-001
          - es
          - es-419
          - es-ar
          - es-bo
          - es-br
          - es-bz
          - es-cl
          - es-co
          - es-cr
          - es-cu
          - es-do
          - es-ea
          - es-ec
          - es-es
          - es-gq
          - es-gt
          - es-hn
          - es-ic
          - es-mx
          - es-ni
          - es-pa
          - es-pe
          - es-ph
          - es-pr
          - es-py
          - es-sv
          - es-us
          - es-uy
          - es-ve
          - et
          - et-ee
          - eu
          - eu-es
          - ewo
          - ewo-cm
          - fa
          - fa-af
          - fa-ir
          - ff
          - ff-bf
          - ff-cm
          - ff-gh
          - ff-gm
          - ff-gn
          - ff-gw
          - ff-lr
          - ff-mr
          - ff-ne
          - ff-ng
          - ff-sl
          - ff-sn
          - fi
          - fi-fi
          - fil
          - fil-ph
          - fo
          - fo-dk
          - fo-fo
          - fr
          - fr-be
          - fr-bf
          - fr-bi
          - fr-bj
          - fr-bl
          - fr-ca
          - fr-cd
          - fr-cf
          - fr-cg
          - fr-ch
          - fr-ci
          - fr-cm
          - fr-dj
          - fr-dz
          - fr-fr
          - fr-ga
          - fr-gf
          - fr-gn
          - fr-gp
          - fr-gq
          - fr-ht
          - fr-km
          - fr-lu
          - fr-ma
          - fr-mc
          - fr-mf
          - fr-mg
          - fr-ml
          - fr-mq
          - fr-mr
          - fr-mu
          - fr-nc
          - fr-ne
          - fr-pf
          - fr-pm
          - fr-re
          - fr-rw
          - fr-sc
          - fr-sn
          - fr-sy
          - fr-td
          - fr-tg
          - fr-tn
          - fr-vu
          - fr-wf
          - fr-yt
          - fur
          - fur-it
          - fy
          - fy-nl
          - ga
          - ga-gb
          - ga-ie
          - gd
          - gd-gb
          - gl
          - gl-es
          - gsw
          - gsw-ch
          - gsw-fr
          - gsw-li
          - gu
          - gu-in
          - guz
          - guz-ke
          - gv
          - gv-im
          - ha
          - ha-gh
          - ha-ne
          - ha-ng
          - haw
          - haw-us
          - he
          - hi
          - hi-in
          - hr
          - hr-ba
          - hr-hr
          - hsb
          - hsb-de
          - hu
          - hu-hu
          - hy
          - hy-am
          - ia
          - ia-001
          - id
          - ig
          - ig-ng
          - ii
          - ii-cn
          - id-id
          - is
          - is-is
          - it
          - it-ch
          - it-it
          - it-sm
          - it-va
          - he-il
          - ja
          - ja-jp
          - jgo
          - jgo-cm
          - yi
          - yi-001
          - jmc
          - jmc-tz
          - jv
          - jv-id
          - ka
          - ka-ge
          - kab
          - kab-dz
          - kam
          - kam-ke
          - kde
          - kde-tz
          - kea
          - kea-cv
          - khq
          - khq-ml
          - ki
          - ki-ke
          - kk
          - kk-kz
          - kkj
          - kkj-cm
          - kl
          - kl-gl
          - kln
          - kln-ke
          - km
          - km-kh
          - kn
          - kn-in
          - ko
          - ko-kp
          - ko-kr
          - kok
          - kok-in
          - ks
          - ks-in
          - ksb
          - ksb-tz
          - ksf
          - ksf-cm
          - ksh
          - ksh-de
          - kw
          - kw-gb
          - ku
          - ku-tr
          - ky
          - ky-kg
          - lag
          - lag-tz
          - lb
          - lb-lu
          - lg
          - lg-ug
          - lkt
          - lkt-us
          - ln
          - ln-ao
          - ln-cd
          - ln-cf
          - ln-cg
          - lo
          - lo-la
          - lrc
          - lrc-iq
          - lrc-ir
          - lt
          - lt-lt
          - lu
          - lu-cd
          - luo
          - luo-ke
          - luy
          - luy-ke
          - lv
          - lv-lv
          - mai
          - mai-in
          - mas
          - mas-ke
          - mas-tz
          - mer
          - mer-ke
          - mfe
          - mfe-mu
          - mg
          - mg-mg
          - mgh
          - mgh-mz
          - mgo
          - mgo-cm
          - mi
          - mi-nz
          - mk
          - mk-mk
          - ml
          - ml-in
          - mn
          - mn-mn
          - mni
          - mni-in
          - mr
          - mr-in
          - ms
          - ms-bn
          - ms-id
          - ms-my
          - ms-sg
          - mt
          - mt-mt
          - mua
          - mua-cm
          - my
          - my-mm
          - mzn
          - mzn-ir
          - naq
          - naq-na
          - nb
          - nb-no
          - nb-sj
          - nd
          - nd-zw
          - nds
          - nds-de
          - nds-nl
          - ne
          - ne-in
          - ne-np
          - nl
          - nl-aw
          - nl-be
          - nl-ch
          - nl-bq
          - nl-cw
          - nl-lu
          - nl-nl
          - nl-sr
          - nl-sx
          - nmg
          - nmg-cm
          - nn
          - nn-no
          - nnh
          - nnh-cm
          - "no"
          - no-no
          - nus
          - nus-ss
          - nyn
          - nyn-ug
          - om
          - om-et
          - om-ke
          - or
          - or-in
          - os
          - os-ge
          - os-ru
          - pa
          - pa-in
          - pa-pk
          - pcm
          - pcm-ng
          - pl
          - pl-pl
          - prg
          - prg-001
          - ps
          - ps-af
          - ps-pk
          - pt
          - pt-ao
          - pt-br
          - pt-ch
          - pt-cv
          - pt-gq
          - pt-gw
          - pt-lu
          - pt-mo
          - pt-mz
          - pt-pt
          - pt-st
          - pt-tl
          - qu
          - qu-bo
          - qu-ec
          - qu-pe
          - rm
          - rm-ch
          - rn
          - rn-bi
          - ro
          - ro-md
          - ro-ro
          - rof
          - rof-tz
          - ru
          - ru-by
          - ru-kg
          - ru-kz
          - ru-md
          - ru-ru
          - ru-ua
          - rw
          - rw-rw
          - rwk
          - rwk-tz
          - sa
          - sa-in
          - sah
          - sah-ru
          - saq
          - saq-ke
          - sat
          - sat-in
          - sbp
          - sbp-tz
          - sd
          - sd-in
          - sd-pk
          - se
          - se-fi
          - se-no
          - se-se
          - seh
          - seh-mz
          - ses
          - ses-ml
          - sg
          - sg-cf
          - shi
          - shi-ma
          - si
          - si-lk
          - sk
          - sk-sk
          - sl
          - sl-si
          - smn
          - smn-fi
          - sn
          - sn-zw
          - so
          - so-dj
          - so-et
          - so-ke
          - so-so
          - sq
          - sq-al
          - sq-mk
          - sq-xk
          - sr
          - sr-ba
          - sr-cs
          - sr-me
          - sr-rs
          - sr-xk
          - su
          - su-id
          - sv
          - sv-ax
          - sv-fi
          - sv-se
          - sw
          - sw-cd
          - sw-ke
          - sw-tz
          - sw-ug
          - sy
          - ta
          - ta-in
          - ta-lk
          - ta-my
          - ta-sg
          - te
          - te-in
          - teo
          - teo-ke
          - teo-ug
          - tg
          - tg-tj
          - th
          - th-th
          - ti
          - ti-er
          - ti-et
          - tk
          - tk-tm
          - tl
          - to
          - to-to
          - tr
          - tr-cy
          - tr-tr
          - tt
          - tt-ru
          - twq
          - twq-ne
          - tzm
          - tzm-ma
          - ug
          - ug-cn
          - uk
          - uk-ua
          - ur
          - ur-in
          - ur-pk
          - uz
          - uz-af
          - uz-uz
          - vai
          - vai-lr
          - vi
          - vi-vn
          - vo
          - vo-001
          - vun
          - vun-tz
          - wae
          - wae-ch
          - wo
          - wo-sn
          - xh
          - xh-za
          - xog
          - xog-ug
          - yav
          - yav-cm
          - yo
          - yo-bj
          - yo-ng
          - yue
          - yue-cn
          - yue-hk
          - zgh
          - zgh-ma
          - zh
          - zh-cn
          - zh-hk
          - zh-mo
          - zh-sg
          - zh-tw
          - zh-hans
          - zh-hant
          - zu
          - zu-za
          type: string
        translatedFromId:
          description: ID of the primary Blog this object was translated from.
          type: string
        publicAccessRules:
          description: Rules for require member registration to access private content.
          items:
            $ref: '#/components/schemas/PublicAccessRule'
          type: array
        publicTitle:
          description: The public title of this Blog.
          type: string
        allowComments:
          description: Boolean determining whether or not this blog allows public
            comments.
          type: boolean
        deletedAt:
          description: The timestamp (ISO8601 format) when this Blog was deleted.
          format: date-time
          type: string
        htmlTitle:
          description: The html title of this Blog.
          type: string
        publicAccessRulesEnabled:
          description: Boolean to determine whether or not to respect publicAccessRules.
          type: boolean
        name:
          description: The internal name of the blog.
          type: string
        id:
          description: The unique ID of the Blog.
          type: string
        updated:
          format: date-time
          type: string
        slug:
          description: The path of the this blog. This field is appended to the domain
            to construct the url of this blog.
          type: string
      required:
      - absoluteUrl
      - allowComments
      - created
      - deletedAt
      - description
      - htmlTitle
      - id
      - language
      - name
      - publicAccessRules
      - publicAccessRulesEnabled
      - publicTitle
      - slug
      - translatedFromId
      - updated
      type: object
    NextPage:
      description: Model definition for a next page.
      example:
        link: link
        after: after
      properties:
        link:
          description: ""
          type: string
        after:
          description: ""
          type: string
      required:
      - after
      type: object
    VersionUser:
      description: Model definition for a VersionUser. Contains addition information
        about the user who created a version.
      example:
        fullName: fullName
        id: id
        email: email
      properties:
        fullName:
          description: The first and last name of the User.
          type: string
        id:
          description: The unique ID of the User.
          type: string
        email:
          description: The email address of the user.
          type: string
      required:
      - email
      - fullName
      - id
      type: object
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            content: Read from and write to my Content
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps:
      in: header
      name: private-app
      type: apiKey
